# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pomo < Formula
  desc "A terminal-based Pomodoro timer with a clean, intuitive interface."
  homepage "https://github.com/maxplumley/pomo"
  version "1.2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/maxplumley/pomo/releases/download/1.2.0/pomo_Darwin_x86_64.tar.gz"
    sha256 "428a3f97df38b9f1c4a85bfbbcc0f138ab3a04e26c029affda0202ec46a9d9f4"

    def install
      bin.install "pomo"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/maxplumley/pomo/releases/download/1.2.0/pomo_Darwin_arm64.tar.gz"
    sha256 "2975e6fb3f9b62ba19745a811e1fe1ca352935acd0bd56452825833127ccd200"

    def install
      bin.install "pomo"
    end
  end

  test do
    system "#{bin}/pomo --version"
  end
end
