# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pomo < Formula
  desc "A terminal-based Pomodoro timer with a clean, intuitive interface."
  homepage "https://github.com/maxplumley/pomo"
  version "1.1.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/maxplumley/pomo/releases/download/1.1.2/pomo_Darwin_x86_64.tar.gz"
    sha256 "04cf0c39ccab09cb21c34024d31a57758662431b1f6a6ed6c58512b0e4e92a1c"

    def install
      bin.install "pomo"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/maxplumley/pomo/releases/download/1.1.2/pomo_Darwin_arm64.tar.gz"
    sha256 "d8d92ca20c306761125a5e00c37a90d2c6f5f212a85550651575a77621ea1c9b"

    def install
      bin.install "pomo"
    end
  end

  test do
    system "#{bin}/pomo --version"
  end
end
